name: Parse External Demo File

on:
  push:
    paths-ignore:
      - '**/*.dem' # No need to trigger on .dem files since we're downloading externally

jobs:
  parse-demo:
    runs-on: ubuntu-latest

    steps:
    # Step to checkout your repository code, needed for scripts and other repo files
    - name: Checkout code
      uses: actions/checkout@v2

    # Step to download the demo file from an external source using wget
    - name: Download the demo file
      run: |
        wget --user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36" https://cs2breakdown.com/demos/heroic-vs-imperial-mirage.dem

    # Setup Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    # Install necessary Python packages
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install demoparser2

    # Parse the downloaded demo file
    - name: Parse demo file
      run: python parse_demo.py

    # Commit and push the generated JSON files
    - name: Commit and push JSON files
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add events/*.json
        git add ticks/*.json
        git add convars/*.json
        git add grenades/*.json
        git add chat/*.json
        git add player_info/*.json
        git add item_drops/*.json
        git add skins/*.json
        
        git commit -m "Add parsed JSON files" || echo "No changes to commit"
        git push
